import type { Metadata } from "next";
import "./globals.css";
import 'lenis/dist/lenis.css'
import { Navbar } from "@/components/layout/nav";
import { Footer7 } from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen w-full`}>
        <Navbar />
        <main className="pt-12 md:pt-16">
          {children}
          <Footer7 />
        </main>
      </body>
    </html>
  );
}
